@extends("layouts.app")

@section("title", "よくあるご質問")
@section("content")
<div class="container">
  <h2 style="text-align:center;">よくあるご質問</h2>
  <br>
  <h1 style="text-align:center;">「(仮)買い物代行サービス」について</h1>
  <div class="container QnA" style="padding:75px; background:#ffffff;">
    <div>
      <table>
        <tr>
          <th>Q.1</th>
          <th>ログインができません。</th>
        </tr>
        <tr>
          <td>A.1</td>
          <td>既にご登録いただいた電話番号かメールアドレスに間違いがないかご確認ください。なお、機種変更などで当該電話番号およびメールアドレスがご利用できなくなった場合には新しい電話番号かメールアドレスでの再登録をお願いします。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.2</th>
          <th>料金について教えてください。</th>
        </tr>
        <tr>
          <td>A.2</td>
          <td>アプリのダウンロードは無料です。買い物を依頼した際には、買い物の実費とサービス料を請求させていただきます。詳細は<u><a href="service_charge">こちら</a></u>からご確認ください。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.3</th>
          <th>支払方法について教えてください。</th>
        </tr>
        <tr>
          <td>A.3</td>
          <td>PayPayでのご決済になります。お支払いは一括払いのみのお取り扱いとなります。ご利用の際は<u><a href="https://paypay.ne.jp/help/c0031/">こちら</a></u>をご参照ください。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.4</th>
          <th>サイトの挙動がおかしいのですが、どうすればいいでしょうか。</th>
        </tr>
        <tr>
          <td>A.4</td>
          <td>ご不便をおかけし申し訳ございません。<br>
            <br>
          以下の対応で症状が改善する可能性がございます。<br>
          ・アプリを再起動する<br>
          ・最新版のアプリにアップデートする<br>
          ・アプリを一度削除し、再度インストールする<br>
          </td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.5</th>
          <th>支払方法について教えてください。</th>
        </tr>
        <tr>
          <td>A.5</td>
          <td>現金でのお支払いとなります。お支払いは一括払いのみのお取り扱いとなります。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.6</th>
          <th>会員情報の変更はできますか。</th>
        </tr>
        <tr>
          <td>A.6</td>
          <td>電話番号やメールアドレス、お名前の変更はできません。パスワードは変更可能です。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.7</th>
          <th>退会する方法を教えてください。</th>
        </tr>
        <tr>
          <td>A.7</td>
          <td><u>こちら</u>からお問い合わせください。</td>
        </tr>
      </table>
    </div>
  </div>
    <br>
  <h1 style="text-align:center;">当サービスについて</h1>
  <div class="container QnA" style="padding:75px; background:#ffffff;">
    <div>
      <table>
        <tr>
          <th>Q.1</th>
          <th>買い物代行サービスとは何ですか。</th>
        </tr>
        <tr>
          <td>A.1</td>
          <td>お客様の代わりに弊社がお店で商品を購入し、ご自宅までお届けするサービスです。大手チェーン店や街の商店といった弊社と連携店するお店であればお買い物ができます。 食料品や日用品はもちろん、車がないと買えないものでもすぐに手に入れることができます。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.2</th>
          <th>連携店とは何ですか。</th>
        </tr>
        <tr>
          <td>A.2</td>
          <td>実際の店舗で扱っている商品を弊社の買い物サービスに掲載いだたいているお店です。お店がおすすめする商品から購入したい商品を簡単に選ぶことができます。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.3</th>
          <th>返品したいのですが。</th>
        </tr>
        <tr>
          <td>A.3</td>
          <td>サービスの性質上、当社に返品を行うことはできません。返品を行う場合には、ご自身で購入店舗に商品とレシートを持参しご対応ください。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.4</th>
          <th>買い物の領収書が欲しい時はどうすればよいですか。</th>
        </tr>
        <tr>
          <td>A.4</td>
          <td>・・・・・。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.5</th>
          <th>買い物先のカードのポイントを貯めたいのですがどうしたらよいでしょうか。</th>
        </tr>
        <tr>
          <td>A.5</td>
          <td>買い物サービスの性質上、現在は店舗とポイントカードの連携は行っておりません。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.6</th>
          <th>サービスに関して問い合わせたいことがあります。</th>
        </tr>
        <tr>
          <td>A.6</td>
          <td>よくあるご質問以外のお問い合わせは<u>こちら</u>からお願いいたします。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.7</th>
          <th>代金の建て替えをしたいのですが、可能でしょうか。</th>
        </tr>
        <tr>
          <td>A.7</td>
          <td>ご依頼いただいた商品代金の建て替えは行っておりません。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.9</th>
          <th>届いた商品に問題があります。（破損、汚損、商品違いなど）</th>
        </tr>
        <tr>
          <td>A.9</td>
          <td>・・・・・。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.10</th>
          <th>再配達について教えてください。</th>
        </tr>
        <tr>
          <td>A.10</td>
          <td>再配達を⾏うことはできません。必ず受け取れる時間を指定してください。不在の場合には置き配となります。</td>
        </tr>
      </table>
    </div>
  </div>
    <br>
  <h1 style="text-align:center;">商品の受け取りについて</h1>
  <div class="container QnA" style="padding:75px; background:#ffffff;">
    <div>
      <table>
        <tr>
          <th>Q.1</th>
          <th>お届け日時を間違えてしまったのですがどのように行えばよいのでしょうか。</th>
        </tr>
        <tr>
          <td>A.1</td>
          <td>ご依頼いただいた後のお届け日時の変更はできません。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.2</th>
          <th>依頼をキャンセルしたいのですがどのように行えばよいのでしょうか。</th>
        </tr>
        <tr>
          <td>A.2</td>
          <td>依頼後はキャンセルを行うことができません。</td>
        </tr>
      </table>
    </div>
    <br>
    <div>
      <table>
        <tr>
          <th>Q.3</th>
          <th>再配達について教えてください。</th>
        </tr>
        <tr>
          <td>A.3</td>
          <td>再配達を⾏うことはできません。必ず受け取れる時間を指定してください。不在の場合には置き配となります。</td>
        </tr>
      </table>
    </div>
</div>
<div style="text-align:center;"><a href="/" class="btn btn-success">戻る</a></div>
@endsection
